name: release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up MSVC x64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: '14.5'
          arch: amd64

      - name: Build python
        id: build-python
        shell: pwsh
        run: |
          ./init.ps1
          ./pack.ps1

      - name: Build minhook
        id: build-minhook
        shell: pwsh
        run: |
          git clone https://github.com/TsudaKageyu/minhook --depth=1 .\third_party\minhook
          cd .\third_party\minhook
          $patchContent = @(
            'if(MSVC)',
            'target_compile_options(minhook PRIVATE',
            '$<$<AND:$<C_COMPILER_ID:MSVC>,$<CONFIG:Debug>>:/MDd>',
            '$<$<AND:$<C_COMPILER_ID:MSVC>,$<NOT:$<CONFIG:Debug>>>:/MD>',  # 匹配 vcxproj 的 /MD
            ')',
            'endif()'
          )
          $patchFile = "CMakeLists.txt"
          $originalContent = Get-Content $patchFile
          $newContent = $originalContent + $patchContent
          Set-Content -Path $patchFile -Value ($newContent -join "`n")

          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --target minhook

          $includePath = "${{ github.workspace }}\version\include"
          $libPath = "${{ github.workspace }}\version\lib"
          if (!(Test-Path $includePath)) { New-Item -ItemType Directory -Path $includePath }
          if (!(Test-Path $libPath)) { New-Item -ItemType Directory -Path $libPath }
          Copy-Item -Path "build\Release\minhook.x64.lib" -Destination $libPath\minhook.x64.lib -Force
          Copy-Item -Path "include\*" -Destination $includePath -Force
      
      - name: Build cpp
        id: build-cpp
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          ./build.ps1

      - name: Prepare artifact
        id: pack
        shell: pwsh
        run: |
          $refName = "${{ github.ref_name }}"
          if ("${{ github.ref_type }}" -ne "tag") {
              $date = Get-Date -Format "yyyyMMdd-HHmm"
              $version = "dev-$date"
          } else {
              $version = $refName
          }
          $newName = "mcbe-pccocos-launcher-$version"
          
          if (Test-Path "python-embed") {
              # 防止因重名目录导致重命名失败
              if (Test-Path $newName) { Remove-Item $newName -Recurse -Force }
              Rename-Item -Path "python-embed" -NewName $newName
          }
          
          $targetPath = "$newName.zip"
          7z a -tzip $targetPath $newName
          "name=$newName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.pack.outputs.name }}
          path: ${{ steps.pack.outputs.name }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ steps.pack.outputs.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}